<a href="https://colab.research.google.com/github/ms-solly/idbi-hackathon-2026/blob/main/notebooks/04_NLP_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP Feature Engineering

## Objective

This notebook generates simple text-based features from synthetic loan officer notes.

These features will later be combined with the structured loan data to improve the XGBoost model.

In [ ]:
import pandas as pd
import numpy as np

!pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.12/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.6.17)

In [ ]:
import pandas as pd
import numpy as np

!pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.12/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.6.17)

In [ ]:
df = pd.read_csv("X_train.csv")

df.head()

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,-0.023737,0.657506,-0.100445,0.711051,-0.077669,-0.671428,-0.063715,-0.016033,-0.057873,1.140084
1,-0.024156,1.402198,-0.100445,-0.168015,-0.199624,-0.477692,-0.063715,-0.016033,-0.057873,-0.666121
2,-0.023344,-1.373472,-0.100445,-0.168152,-0.206067,-0.090221,-0.063715,-0.898607,-0.057873,1.140084
3,-0.020244,0.522107,-0.100445,-0.111893,-0.077669,-0.671428,-0.063715,-0.898607,-0.057873,-0.666121
4,-0.023281,0.522107,-0.100445,-0.167767,-0.260985,0.297250,-0.063715,-0.016033,-0.057873,-0.666121

In [ ]:
notes = [
    "Customer has stable salary and pays EMI on time.",
    "Income verified and repayment history is good.",
    "Customer missed several EMI payments recently.",
    "Business income is unstable and documents are incomplete.",
    "Regular salary credits and good banking behaviour."
]

df["loan_notes"] = [notes[i % len(notes)] for i in range(len(df))]

In [ ]:
df[["loan_notes"]].head()

                                          loan_notes
0   Customer has stable salary and pays EMI on time.
1     Income verified and repayment history is good.
2     Customer missed several EMI payments recently.
3  Business income is unstable and documents are ...
4  Regular salary credits and good banking behavi...

In [ ]:
analyzer = SentimentIntensityAnalyzer()

df["sentiment_score"] = df["loan_notes"].apply(
    lambda x: analyzer.polarity_scores(x)["compound"]
)

In [ ]:
df[["loan_notes", "sentiment_score"]].head()

                                          loan_notes  sentiment_score
0   Customer has stable salary and pays EMI on time.           0.2960
1     Income verified and repayment history is good.           0.4404
2     Customer missed several EMI payments recently.          -0.2960
3  Business income is unstable and documents are ...          -0.3612
4  Regular salary credits and good banking behavi...           0.6597

In [ ]:
keywords = [
    "missed",
    "late",
    "default",
    "overdue",
    "unstable",
    "incomplete"
]

def keyword_flag(text):
    text = text.lower()
    return int(any(word in text for word in keywords))

df["negative_keyword_flag"] = df["loan_notes"].apply(keyword_flag)

In [ ]:
df[["loan_notes", "negative_keyword_flag"]].head()

                                          loan_notes  negative_keyword_flag
0   Customer has stable salary and pays EMI on time.                      0
1     Income verified and repayment history is good.                      0
2     Customer missed several EMI payments recently.                      1
3  Business income is unstable and documents are ...                      1
4  Regular salary credits and good banking behavi...                      0

In [ ]:
df.to_csv("X_train_with_nlp.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!